title: Abdul Subhan Soomro
logo: /assets/img/cropped_circle_image.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
[Linkedin](https://www.linkedin.com/in/subhan3w/)
Tel: +92 333 1338035
email: subhansoomro99@gmail.com
